spring.application.name=demo

# Change to MySQL URL (3306 is default MySQL port)
spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC

# MySQL credentials
spring.datasource.username=root
spring.datasource.password=Eq11223344

# Hibernate dialect for MySQL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
